POST http://localhost:3000/api/inscripcion/
Content-Type: application/json


{
"alumnoId":"655e535c4117f4b0afc821ff",
"materiaId":"654bd4d101fbcb278b490d87",
"fechaHoraInscripcion": "2023-11-22T19:17:42.683Z"
}
